---

- name: check if destination already exists 
  stat: path={{ newrole_dest }}/{{ newrole_name }}
  register: already_exists
  changed_when: false

- name: fail - destination already exists!!
  fail: 
    msg: "Looks like the destination already exists!!! {{ newrole_dest }}/{{ newrole_name }}  We don't want to overwrite your existing code, so we're going to fail instead. Please check that the destination doesn't exist or remove it if you want to create it anew."
  when: already_exists.stat.exists and not newrole_force

# tasks file for newrole
- name: destination folder
  file:
    state=directory
    path={{ newrole_dest }}/{{ newrole_name }}

- name: create folders
  file:
    state=directory
    path={{ newrole_dest }}/{{ newrole_name }}/{{ item }}
  with_items:
    - defaults
    - files
    - handlers
    - meta
    - tasks
    - templates

- name: create main.yml files
  file:
    state=touch
    path={{ newrole_dest }}/{{ newrole_name }}/{{ item }}
  with_items:
    - defaults/main.yml
    - handlers/main.yml
    - tasks/config.yml
    - tasks/depend.yml
    - tasks/install_debian.yml
    - tasks/service.yml
  changed_when: False

- name: meta/main.yml
  template:
    src=meta_main.yml.j2
    dest={{ newrole_dest }}/{{ newrole_name }}/meta/main.yml

- name: ansible.cfg and bumpversion
  copy:
    src={{ item }}
    dest={{ newrole_dest }}/{{ newrole_name }}/{{ item }}
  with_items:
    - ansible.cfg
    - bumpversion

- name: make bumpversion executable
  file:
    path={{ newrole_dest }}/{{ newrole_name }}/bumpversion
    mode=0755

- name: create hidden files .travis.yml and .bumpversion.cfg
  copy:
    src={{ item }}
    dest={{ newrole_dest }}/{{ newrole_name }}/.{{ item }}
  with_items:
    - travis.yml
    - bumpversion.cfg

- name: Vagrantfile, test.yml and README.md
  template:
    src={{item}}.j2
    dest={{ newrole_dest }}/{{ newrole_name }}/{{ item }}
  with_items:
    - Vagrantfile
    - test.yml
    - README.md

- name: tasks/main.yml
  copy:
    src=tasks_main.yml
    dest={{ newrole_dest }}/{{ newrole_name }}/tasks/main.yml



